name: Test

on:
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Cache ffmpeg build
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: |
            src/**.a
            src/ffmpeg/**.a
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('src/ffmpeg/RELEASE') }}

      - if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
        name: Build ffmpeg & libffmpeg
        working-directory: ./src/ffmpeg
        run: |
          brew install automake shtool texi2html wget nasm
          ./configure
          make -j4
          cd ..
          make libffmpeg.a

      - name: npm
        run: |
          npm install -g node-gyp
          npm i --ignore-scripts

      - name: Prebuild
        run: npx prebuildify --napi

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-mac
          path: prebuilds

  build-win:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          release: false
          install: >-
            make
            pkgconf
            diffutils
            nasm
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Cache ffmpeg build
        id: cache-ffmpeg
        uses: actions/cache@v3
        with:
          path: |
            src/**.a
            src/ffmpeg/**.a
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('src/ffmpeg/RELEASE') }}
          
      - if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
        name: Build ffmpeg & libffmpeg
        working-directory: ./src
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          msys2 -c "./win/build.sh"
        shell: cmd

      - name: npm
        run: |
          npm install -g node-gyp
          npm i --ignore-scripts

      - name: Prebuild
        run: npx prebuildify --napi
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prebuild-win
          path: prebuilds
