name: Test

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true

      # Runs a single command using the runners shell
      - name: Build ffmpeg
        working-directory: ./src/ffmpeg
        run: |
          brew install automake shtool texi2html wget nasm
          ./configure
          make -j4

      - name: Build libffmpeg
        working-directory: ./src
        run: |
          make libffmpeg.a
