name: Test

on:
  workflow_dispatch:

jobs:
  # build:
  #   # The type of runner that the job will run on
  #   runs-on: macos-latest

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3
  #       with:
  #         submodules: true

  #     # Runs a single command using the runners shell
  #     - name: Build ffmpeg
  #       working-directory: ./src/ffmpeg
  #       run: |
  #         brew install automake shtool texi2html wget nasm
  #         ./configure
  #         make -j4

  #     - name: Build libffmpeg
  #       working-directory: ./src
  #       run: |
  #         make libffmpeg.a

  build-win:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MSYS
          path-type: inherit
          release: false
          install: >-
            make
            pkgconf
            diffutils
            nasm

      # Runs a single command using the runners shell
      - name: Build ffmpeg
        working-directory: ./src
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
          msys2 -c "./win/build.sh"
        shell: cmd

      # - name: Build libffmpeg
      #   working-directory: ./src
      #   run: |
      #     make libffmpeg.a
